spring:
  datasource:
    dynamic:
      primary: master  # 默认数据源
      strict: false    # 关闭严格模式（开发阶段建议关闭，避免未配置数据源时报错）
      datasource:
        master:
          url: jdbc:mysql://120.24.30.157:3306/mydb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://120.24.30.157:3307/mydb_slave?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL（开发用）
  global-config:
    db-config:
      id-type: auto  # 主键自增